time:
  user_timezone: "Europe/Moscow"
  window: "calendar_day"

ews:
  endpoint: "https://owa.corp-domain.ru/EWS/Exchange.asmx"
  user_upn: "login@corp-domain.ru"
  user_login: "login"
  user_domain: "corp-domain.ru"
  password_env: "EWS_PASSWORD"
  verify_ca: "/etc/ssl/corp-ca.pem"
  autodiscover: false
  folders: ["Inbox"]
  lookback_hours: 24
  page_size: 100
  sync_state_path: ".state/ews.syncstate"
  user_aliases: ["alias1@corp-domain.ru", "alias2@corp-domain.ru"]

llm:
  endpoint: "https://llm-gw.corp.com/api/v1/chat"
  model: "Qwen/Qwen3-30B-A3B-Instruct-2507"
  timeout_s: 60
  headers:
    Authorization: "Bearer ${LLM_TOKEN}"
  max_tokens_per_run: 30000
  cost_limit_per_run: 5.0

observability:
  prometheus_port: 9108
  log_level: "INFO"

selection_buckets:
  threads_top: 10           # Minimum threads to cover (1 chunk each)
  addressed_to_me: 8        # Minimum chunks with AddressedToMe=true
  dates_deadlines: 6        # Minimum chunks with dates/deadlines
  critical_senders: 4       # Minimum chunks from sender_rank>=2
  per_thread_max: 3         # Maximum chunks per thread
  max_total_chunks: 20      # Maximum total chunks to select

selection_weights:
  recency: 2.0              # Weight for message recency
  addressed_to_me: 3.0      # Weight for AddressedToMe flag
  action_verbs: 1.5         # Weight per action verb found
  question_mark: 1.0        # Weight for questions
  dates_found: 1.5          # Weight per date/deadline found
  importance_high: 2.0      # Weight for High importance
  is_flagged: 1.5           # Weight for flagged messages
  has_doc_attachments: 1.0  # Weight for doc/xlsx/pdf attachments
  sender_rank: 1.0          # Weight multiplier per sender rank level
  thread_activity: 0.5      # Weight for thread activity
  negative_prior: -2.0      # Penalty for noreply/unsubscribe patterns
