time:
  user_timezone: "Europe/Moscow"
  window: "calendar_day"
  mailbox_tz: "Europe/Moscow"      # Mailbox timezone for normalizing naive datetime
  runner_tz: "America/Sao_Paulo"   # Runner/job timezone
  fail_on_naive: true              # Fail if naive datetime is encountered

ews:
  endpoint: "https://owa.corp-domain.ru/EWS/Exchange.asmx"
  user_upn: "login@corp-domain.ru"
  user_login: "login"
  user_domain: "corp-domain.ru"
  password_env: "EWS_PASSWORD"
  verify_ca: "/etc/ssl/corp-ca.pem"
  autodiscover: false
  folders: ["Inbox"]
  lookback_hours: 24
  page_size: 100
  sync_state_path: ".state/ews.syncstate"
  user_aliases: ["alias1@corp-domain.ru", "alias2@corp-domain.ru"]

llm:
  endpoint: "https://llm-gw.corp.com/api/v1/chat"
  model: "Qwen/Qwen3-30B-A3B-Instruct-2507"
  timeout_s: 60
  headers:
    Authorization: "Bearer ${LLM_TOKEN}"
  max_tokens_per_run: 30000
  cost_limit_per_run: 5.0
  strict_json: true          # Enforce strict JSON validation with Pydantic
  max_retries: 3             # Maximum retry attempts for invalid JSON

observability:
  prometheus_port: 9108
  log_level: "INFO"

selection_buckets:
  threads_top: 10           # Minimum threads to cover (1 chunk each)
  addressed_to_me: 8        # Minimum chunks with AddressedToMe=true
  dates_deadlines: 6        # Minimum chunks with dates/deadlines
  critical_senders: 4       # Minimum chunks from sender_rank>=2
  per_thread_max: 3         # Maximum chunks per thread
  max_total_chunks: 20      # Maximum total chunks to select

selection_weights:
  recency: 2.0              # Weight for message recency
  addressed_to_me: 3.0      # Weight for AddressedToMe flag
  action_verbs: 1.5         # Weight per action verb found
  question_mark: 1.0        # Weight for questions
  dates_found: 1.5          # Weight per date/deadline found
  importance_high: 2.0      # Weight for High importance
  is_flagged: 1.5           # Weight for flagged messages
  has_doc_attachments: 1.0  # Weight for doc/xlsx/pdf attachments
  sender_rank: 1.0          # Weight multiplier per sender rank level
  thread_activity: 0.5      # Weight for thread activity
  negative_prior: -2.0      # Penalty for noreply/unsubscribe patterns

context_budget:
  max_total_tokens: 7000    # Maximum total tokens for LLM input
  per_thread_max: 3         # Maximum chunks per thread

chunking:
  long_email_tokens: 1000   # Threshold for long email
  max_chunks_if_long: 3     # Max chunks for long emails
  max_chunks_default: 12    # Default max chunks per message
  adaptive_high_load_emails: 200  # Email count threshold for high load
  adaptive_high_load_threads: 60  # Thread count threshold for high load
  adaptive_multiplier: 0.75 # Multiplier for high load

shrink:
  enable_auto_shrink: true  # Enable auto-shrink on overflow
  preserve_min_quotas: true # Preserve minimum bucket quotas during shrink

hierarchical:
  enable: true              # Enable hierarchical mode
  enable_auto: true         # Enable automatic hierarchical mode activation
  threshold_threads: 40     # Thread count threshold for auto activation (умеренный порог)
  threshold_emails: 200     # Email count threshold for auto activation
  min_threads_to_summarize: 6  # Minimum threads required to use hierarchical mode
  min_threads: 30           # Min threads to activate (deprecated, use threshold_threads)
  min_emails: 150           # Min emails to activate (deprecated, use threshold_emails)
  per_thread_max_chunks_in: 8  # Max chunks per thread for summarization
  summary_max_tokens: 90    # Max tokens for thread summary
  parallel_pool: 8          # Max parallel thread summarization workers
  timeout_sec: 20           # Timeout per thread summarization
  degrade_on_timeout: "best_2_chunks"  # Degradation strategy on timeout
  final_input_token_cap: 4000  # Max tokens for final aggregator input
  max_latency_increase_pct: 50  # Max acceptable latency increase %
  target_latency_increase_pct: 30  # Target latency increase %
  max_cost_increase_per_email_pct: 40  # Max acceptable cost increase per email %

masking:
  enforce_input: true       # Enforce PII masking before LLM
  enforce_output: true      # Validate no PII in LLM output

degrade:
  enable: true              # Enable degradation on LLM failures
  mode: "extractive"        # Degradation mode: extractive | empty
